-- toolchain("gcc-trunk")
--     set_kind("standalone")
--     local sdkdir = path.join(os.getenv("HOME"), "opt/gcc-trunk")
--     set_sdkdir(sdkdir)
--     set_bindir(path.join(sdkdir, "bin"))
--     set_toolset("cc", "gcc")
--     set_toolset("cxx", "g++")
--     set_toolset("ld", "g++")
--     set_toolset("sh", "g++")
--     set_toolset("ar", "gcc-ar")
--     set_toolset("ranlib", "gcc-ranlib")
--     add_linkdirs(path.join(sdkdir, "lib64"))
--     add_rpathdirs(path.join(sdkdir, "lib64"))
-- toolchain_end()

add_rules("mode.debug", "mode.release")
-- set_toolchains("gcc-trunk")
set_languages("c++26")
set_encodings("utf-8")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

target("binproto")
    set_kind("binary")
    add_cxflags("-freflection", {force = true})
    add_files("src/*.cc")
    add_includedirs("include")

